version: '3'

services: 
    rails:
        container_name: rails
        build: 
            context: .
            dockerfile: ./Dockerfile
        volumes: 
            - .:/mussertion
            - ./entrypoint.sh /usr/bin/
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        # pumaを実行するコマンド
        #command: bundle exec puma -C config/puma.rb

    nginx: 
        container_name: nginx
        build: 
            context: .
            dockerfile: ./docker/dev/app/nginx/Dockerfile
        volumes: 
            - .:/mussertion
        ports: 
            - 80:80

    mysql: 
        image: mysql:8.0
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mussertion
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            TZ: 'Asia/Tokyo'
        volumes: 
            - rails-db:/var/lib/mysql/
            - ./docker/dev/app/mysql/my.cof:/etc/mysql/my.cnf
        ports: 
            - 3306:3306

volumes: 
    rails-db: 